apiVersion: v1
kind: Namespace
metadata:
  name: $KUBE_NAMESPACE
---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: $CI_PROJECT_NAME
spec:
  selector:
    matchLabels:
      name: $CI_PROJECT_NAME
  template:
    metadata:
      labels:
        name: $CI_PROJECT_NAME
    spec:
      serviceAccountName: pv-reader
      containers:
      - name: $CI_PROJECT_NAME
        image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
        ports:
        - name: metrics
          containerPort: 9100
          protocol: TCP
        env:
        - name: CI_COMMIT_REF_NAME
          value: "$CI_COMMIT_REF_NAME"
        - name: CI_COMMIT_SHORT_SHA
          value: "$CI_COMMIT_SHORT_SHA"
        volumeMounts:
        - name: pvs-dir
          mountPath: /var/lib/rancher/k3s/storage/
      volumes:
      - name: pvs-dir
        hostPath:
          path: /var/lib/rancher/k3s/storage/
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_PROJECT_NAME
spec:
  selector:
    name: $CI_PROJECT_NAME
  type: NodePort
  ports:
  - port: 9100
    name: metrics
    targetPort: metrics
    nodePort: 60100
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-reader
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pv-reader
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pv-reader-binding
subjects:
- kind: ServiceAccount
  name: pv-reader
  namespace: $KUBE_NAMESPACE
roleRef:
  kind: ClusterRole
  name: pv-reader
  apiGroup: rbac.authorization.k8s.io