{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pv-exporter.fullname" . }}
  labels: {{- include "pv-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch

{{- if .Values.rbac.rules }}
{{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end -}}
{{- end }}