apiVersion: v1
kind: Service
metadata:
  name: {{ include "pv-exporter.fullname" . }}
  labels:
    {{- include "pv-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and .Values.service.type "NodePort" .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pv-exporter.selectorLabels" . | nindent 4 }}
