name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-docker-image:
    name: Build Docker image and push to the registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.CR_USERNAME }}
        password: ${{ secrets.CR_PAT }}

    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: .
        # Note: tags has to be all lower-case
        tags: ghcr.io/ahmadidev/k8s-pv-metrics-exporter:latest
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
